2025-05-22 18:47:37,689 ERROR: Row 748: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "student_aadhar_number_key"
DETAIL:  Key (aadhar_number)=(684639241194) already exists.

[SQL: INSERT INTO student (pen_num, admission_number, aadhar_number, student_name, father_name, mother_name, gender, date_of_birth, date_of_joining, contact_number, village, created_by, updated_at, updated_by) VALUES (%(pen_num)s, %(admission_number)s, %(aadhar_number)s, %(student_name)s, %(father_name)s, %(mother_name)s, %(gender)s, %(date_of_birth)s, %(date_of_joining)s, %(contact_number)s, %(village)s, %(created_by)s, %(updated_at)s, %(updated_by)s) RETURNING student.created_at]
[parameters: {'pen_num': 20976697950, 'admission_number': 1539, 'aadhar_number': 684639241194, 'student_name': 'Sajja Thrunith Chowdry', 'father_name': 'Sajja Vijay Kumar', 'mother_name': 'Sajja Divya', 'gender': 'Male', 'date_of_birth': datetime.date(2012, 10, 17), 'date_of_joining': datetime.date(2022, 5, 24), 'contact_number': '6281446585', 'village': 'Hythabad', 'created_by': 'Uthkarsh', 'updated_at': datetime.datetime(2025, 5, 22, 18, 47, 37, 681247), 'updated_by': 'Uthkarsh'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a) [in /media/uthkarsh/HDD1/school_fee/school_final/school/routes.py:1208]
2025-05-22 18:47:37,689 ERROR: Row 749: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "student_aadhar_number_key"
DETAIL:  Key (aadhar_number)=(684639241194) already exists.

[SQL: INSERT INTO student (pen_num, admission_number, aadhar_number, student_name, father_name, mother_name, gender, date_of_birth, date_of_joining, contact_number, village, created_by, updated_at, updated_by) VALUES (%(pen_num)s, %(admission_number)s, %(aadhar_number)s, %(student_name)s, %(father_name)s, %(mother_name)s, %(gender)s, %(date_of_birth)s, %(date_of_joining)s, %(contact_number)s, %(village)s, %(created_by)s, %(updated_at)s, %(updated_by)s) RETURNING student.created_at]
[parameters: {'pen_num': 20976697950, 'admission_number': 1539, 'aadhar_number': 684639241194, 'student_name': 'Sajja Thrunith Chowdry', 'father_name': 'Sajja Vijay Kumar', 'mother_name': 'Sajja Divya', 'gender': 'Male', 'date_of_birth': datetime.date(2012, 10, 17), 'date_of_joining': datetime.date(2022, 5, 24), 'contact_number': '6281446585', 'village': 'Hythabad', 'created_by': 'Uthkarsh', 'updated_at': datetime.datetime(2025, 5, 22, 18, 47, 37, 681247), 'updated_by': 'Uthkarsh'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a) [in /media/uthkarsh/HDD1/school_fee/school_final/school/routes.py:1208]
2025-05-22 18:47:37,690 ERROR: Row 750: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "student_aadhar_number_key"
DETAIL:  Key (aadhar_number)=(684639241194) already exists.

[SQL: INSERT INTO student (pen_num, admission_number, aadhar_number, student_name, father_name, mother_name, gender, date_of_birth, date_of_joining, contact_number, village, created_by, updated_at, updated_by) VALUES (%(pen_num)s, %(admission_number)s, %(aadhar_number)s, %(student_name)s, %(father_name)s, %(mother_name)s, %(gender)s, %(date_of_birth)s, %(date_of_joining)s, %(contact_number)s, %(village)s, %(created_by)s, %(updated_at)s, %(updated_by)s) RETURNING student.created_at]
[parameters: {'pen_num': 20976697950, 'admission_number': 1539, 'aadhar_number': 684639241194, 'student_name': 'Sajja Thrunith Chowdry', 'father_name': 'Sajja Vijay Kumar', 'mother_name': 'Sajja Divya', 'gender': 'Male', 'date_of_birth': datetime.date(2012, 10, 17), 'date_of_joining': datetime.date(2022, 5, 24), 'contact_number': '6281446585', 'village': 'Hythabad', 'created_by': 'Uthkarsh', 'updated_at': datetime.datetime(2025, 5, 22, 18, 47, 37, 681247), 'updated_by': 'Uthkarsh'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a) [in /media/uthkarsh/HDD1/school_fee/school_final/school/routes.py:1208]
2025-05-22 18:47:37,691 ERROR: Failed to commit batch 15: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "student_aadhar_number_key"
DETAIL:  Key (aadhar_number)=(684639241194) already exists.

[SQL: INSERT INTO student (pen_num, admission_number, aadhar_number, student_name, father_name, mother_name, gender, date_of_birth, date_of_joining, contact_number, village, created_by, updated_at, updated_by) VALUES (%(pen_num)s, %(admission_number)s, %(aadhar_number)s, %(student_name)s, %(father_name)s, %(mother_name)s, %(gender)s, %(date_of_birth)s, %(date_of_joining)s, %(contact_number)s, %(village)s, %(created_by)s, %(updated_at)s, %(updated_by)s) RETURNING student.created_at]
[parameters: {'pen_num': 20976697950, 'admission_number': 1539, 'aadhar_number': 684639241194, 'student_name': 'Sajja Thrunith Chowdry', 'father_name': 'Sajja Vijay Kumar', 'mother_name': 'Sajja Divya', 'gender': 'Male', 'date_of_birth': datetime.date(2012, 10, 17), 'date_of_joining': datetime.date(2022, 5, 24), 'contact_number': '6281446585', 'village': 'Hythabad', 'created_by': 'Uthkarsh', 'updated_at': datetime.datetime(2025, 5, 22, 18, 47, 37, 681247), 'updated_by': 'Uthkarsh'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a) [in /media/uthkarsh/HDD1/school_fee/school_final/school/routes.py:1219]
2025-05-22 18:47:37,691 INFO: Processing batch 16 (rows 751-800) [in /media/uthkarsh/HDD1/school_fee/school_final/school/routes.py:1113]
2025-05-22 18:47:37,701 WARNING: Using current date for unparseable joining date: 31.032022 [in /media/uthkarsh/HDD1/school_fee/school_final/school/models.py:252]
2025-05-22 18:47:37,720 WARNING: Using current date for unparseable joining date: 25.062022 [in /media/uthkarsh/HDD1/school_fee/school_final/school/models.py:252]
2025-05-22 18:47:37,729 ERROR: Row 779: Invalid number format: Aadhar number must be 12 digits [in /media/uthkarsh/HDD1/school_fee/school_final/school/routes.py:1208]
2025-05-22 18:47:37,752 ERROR: Row 798: Invalid number format: Aadhar number must be 12 digits [in /media/uthkarsh/HDD1/school_fee/school_final/school/routes.py:1208]
2025-05-22 18:47:37,757 INFO: Committed batch 16: 48 successful, 2 failed [in /media/uthkarsh/HDD1/school_fee/school_final/school/routes.py:1215]
2025-05-22 18:47:37,757 INFO: Processing batch 17 (rows 801-850) [in /media/uthkarsh/HDD1/school_fee/school_final/school/routes.py:1113]
2025-05-22 18:47:37,784 WARNING: Using current date for unparseable joining date: 27.04. 2019 [in /media/uthkarsh/HDD1/school_fee/school_final/school/models.py:252]
2025-05-22 18:47:37,806 ERROR: Row 839: Invalid number format: Aadhar number must be 12 digits [in /media/uthkarsh/HDD1/school_fee/school_final/school/routes.py:1208]
2025-05-22 18:47:37,813 ERROR: Row 844: Invalid number format: Aadhar number must be 12 digits [in /media/uthkarsh/HDD1/school_fee/school_final/school/routes.py:1208]
2025-05-22 18:47:37,824 INFO: Committed batch 17: 48 successful, 2 failed [in /media/uthkarsh/HDD1/school_fee/school_final/school/routes.py:1215]
2025-05-22 18:47:37,824 INFO: Processing batch 18 (rows 851-900) [in /media/uthkarsh/HDD1/school_fee/school_final/school/routes.py:1113]
2025-05-22 18:47:37,832 WARNING: Using current date for unparseable joining date: 23.05. 2022 [in /media/uthkarsh/HDD1/school_fee/school_final/school/models.py:252]
2025-05-22 18:47:37,840 WARNING: Using current date for unparseable joining date: 17.06. 2019 [in /media/uthkarsh/HDD1/school_fee/school_final/school/models.py:252]
2025-05-22 18:47:37,852 WARNING: Using current date for unparseable joining date: 10. 06.2022 [in /media/uthkarsh/HDD1/school_fee/school_final/school/models.py:252]
2025-05-22 18:47:37,890 INFO: Committed batch 18: 50 successful, 0 failed [in /media/uthkarsh/HDD1/school_fee/school_final/school/routes.py:1215]
2025-05-22 18:47:37,890 INFO: Processing batch 19 (rows 901-950) [in /media/uthkarsh/HDD1/school_fee/school_final/school/routes.py:1113]
2025-05-22 18:47:37,905 ERROR: Row 910: Invalid number format: Aadhar number must be 12 digits [in /media/uthkarsh/HDD1/school_fee/school_final/school/routes.py:1208]
2025-05-22 18:47:37,956 INFO: Committed batch 19: 49 successful, 1 failed [in /media/uthkarsh/HDD1/school_fee/school_final/school/routes.py:1215]
2025-05-22 18:47:37,956 INFO: Processing batch 20 (rows 951-1000) [in /media/uthkarsh/HDD1/school_fee/school_final/school/routes.py:1113]
2025-05-22 18:47:37,981 WARNING: Using default date of birth for unparseable value: 2010-60-02 [in /media/uthkarsh/HDD1/school_fee/school_final/school/models.py:249]
