2025-05-12 03:26:41,560 ERROR: Exception on /student_form [GET] [in /media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column users.last_login does not exist
LINE 1: ...password, users.is_approved AS users_is_approved, users.last...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/flask_login/utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/werkzeug/local.py", line 526, in _get_current_object
    return get_name(local())
                    ^^^^^^^
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ^^^^^^^^^^^
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/flask_login/login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/uthkarsh/HDD1/school_fee/school_final/school/models.py", line 9, in load_user
    return User.query.get(int(user_id))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in get
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 386, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 1121, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 1130, in _get_impl
    return self.session._get_impl(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3874, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 694, in load_on_pk_identity
    session.execute(
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/media/uthkarsh/HDD1/school_fee/school_final/.school/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column users.last_login does not exist
LINE 1: ...password, users.is_approved AS users_is_approved, users.last...
                                                             ^

[SQL: SELECT users.id AS users_id, users.username AS users_username, users.email AS users_email, users.user_role AS users_user_role, users.password AS users_password, users.is_approved AS users_is_approved, users.last_login AS users_last_login, users.failed_login_attempts AS users_failed_login_attempts, users.account_locked_until AS users_account_locked_until 
FROM users 
WHERE users.id = %(pk_1)s]
[parameters: {'pk_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405)
